services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=subscriptions
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    depends_on:
      - postgres
    working_dir: /app

volumes:
  postgres_data:
